In [1]:
import pandas as pd
df = pd.read_csv("cardekho_imputated.csv")
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [2]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [3]:
# from what we see we have 3 column for car name, brand name and model. we can only keep model
df.drop(columns=['car_name','brand','Unnamed: 0'], axis=1, inplace=True)
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [5]:
# Getting all different types of features
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.3+ MB

In [6]:
num_features = [feature for feature in df.columns if df[feature].dtype != "O" ]
cat_feature = [feature for feature in df.columns if df[feature].dtype == "O"]

In [7]:
discrete_feature = [feature for feature in num_features if len(df[feature].unique()) <= 25 ]
continuous_feature = [feature for feature in num_features if feature not in discrete_feature]

In [8]:
continuous_feature

['km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [9]:
discrete_feature

['vehicle_age', 'seats']

### Split the dataset in X & Y

In [10]:
from sklearn.model_selection import train_test_split
X = df.drop('selling_price', axis=1)
Y = df['selling_price']

#### Apply label encoding
this is done because we see model column hv 120 repetitive elements. instead of apply ohe we do label encoding.
label encoder apply labels for eg: [1,1,3,6] -> [0,0,1,2]

In [11]:
from sklearn.preprocessing import LabelEncoder
ls = LabelEncoder()
X['model'] = ls.fit_transform(X['model'])

In [12]:
#as we see our X is having labels as model
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

#### OHE will create 119 extra columns thats why we went with labels approach.

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  int64
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
dtypes: float64(2), int64(5), object(3)
memory usage: 1.2+ MB

In [14]:
# alternatively num_features = [feature for feature in X.columns if X[feature].dtype != "O" ]
cat_feature = X.select_dtypes('object')
num_feature = X.select_dtypes(exclude='object')

In [15]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

ohe = OneHotEncoder(drop='first')
ss = StandardScaler()

preprocessor = ColumnTransformer(
    [
        ("ohe", ohe, cat_feature.columns),
        ("StandardScaler", ss, num_feature.columns)
    ], remainder= "passthrough"
)

In [16]:
preprocessor
# cat_feature.head()
# num_feature.info()

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe', OneHotEncoder(drop='first'),
                                 Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power',
       'seats'],
      dtype='object'))])

In [17]:
pd.DataFrame(X)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
15406,117,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,42,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,77,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,114,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,25,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [18]:
X = preprocessor.fit_transform(X)
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

### Model training and model selection

In [20]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import root_mean_squared_error,mean_absolute_error,mean_squared_error,r2_score

In [21]:
# create a function to evaluate metrics
def evaluatin(true,pred):
    rmse = root_mean_squared_error(true,pred)
    mae = mean_absolute_error(true,pred)
    mse = mean_squared_error(true,pred)
    r2_square = r2_score(true, pred)
    return rmse,mae,mse, r2_square

In [22]:
# Creating models
models = {
    "RandomForestRegressor": RandomForestRegressor(),
    "DecisionTreeRegressor": DecisionTreeRegressor(),
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "KNeighborsRegressor": KNeighborsRegressor()
}

In [23]:
list(models.values())[1]

DecisionTreeRegressor()

In [24]:
for i in range(len(models)):
    model = list(models.values())[i]

    model.fit(X_train,Y_train) # train model
    # test models
    X_train_pred = model.predict(X_train)
    X_test_pred = model.predict(X_test)
    
    rmse,mae,mse, r2_square = evaluatin(Y_train, X_train_pred)

    print( "selected model is:", model)
    print("values for Train is:")
    print ( "root_mean_squared_error: ", format(rmse))
    print ( "mean absolute error:", format(mae))
    print("mean squared error", format(mse))
    print( "r2 score", format(r2_square))

    rmse,mae,mse, r2_square = evaluatin(Y_test, X_test_pred)

    print("values for Test is:")
    print ("root_mean_squared_error: ", format(rmse))
    print ( "mean absolute error:", format(mae))
    print("mean squared error", format(mse))
    print( "r2 score", format(r2_square))
    print('\n')
    print('\n')

selected model is: RandomForestRegressor()
values for Train is:
root_mean_squared_error:  130122.93614056119
mean absolute error: 39670.73183308913
mean squared error 16931978509.840563
r2 score 0.979122993486339
values for Test is:
root_mean_squared_error:  225033.52338224134
mean absolute error: 101503.8036790488
mean squared error 50640086645.82576
r2 score 0.9327293947781069




selected model is: DecisionTreeRegressor()
values for Train is:
root_mean_squared_error:  20797.23516567643
mean absolute error: 5164.819922128488
mean squared error 432524990.53644824
r2 score 0.9994666998284044
values for Test is:
root_mean_squared_error:  308911.8776454755
mean absolute error: 125077.83814466429
mean squared error 95426548150.45322
r2 score 0.8732347815039481




selected model is: LinearRegression()
values for Train is:
root_mean_squared_error:  553855.6665411663
mean absolute error: 268101.60708299355
mean squared error 306756099359.7596
r2 score 0.6217719576765959
values for Test is:
root_mean_squared_error:  502543.59302309836
mean absolute error: 279618.5794158427
mean squared error 252550062888.56552
r2 score 0.6645109298852006




selected model is: Ridge()
values for Train is:
root_mean_squared_error:  553856.3159709624
mean absolute error: 268059.80146883114
mean squared error 306756818740.9266
r2 score 0.6217710706848425
values for Test is:
root_mean_squared_error:  502533.8229890289
mean absolute error: 279557.2168930274
mean squared error 252540243247.96863
r2 score 0.6645239743566809




selected model is: Lasso()
values for Train is:
root_mean_squared_error:  553855.6709544231
mean absolute error: 268099.2226498115
mean squared error 306756104248.3742
r2 score 0.6217719516489697
values for Test is:
root_mean_squared_error:  502542.66963789385
mean absolute error: 279614.7461034126
mean squared error 252549134806.78134
r2 score 0.6645121627547996




selected model is: KNeighborsRegressor()
values for Train is:
root_mean_squared_error:  325885.9831001957
mean absolute error: 91430.97014925373
mean squared error 106201673981.18105
r2 score 0.8690541073993072
values for Test is:
root_mean_squared_error:  253071.94275810325
mean absolute error: 112672.89166396367
mean squared error 64045408211.36069
r2 score 0.914921682456944

### HyperParameter Tuning
we observed best performance was given by k nearest and random forest regression

In [31]:

kn_params = {"n_neighbors": [2,3,10,20,30,40]}
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, None, 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]
            }

In [32]:
random_cv_model = [
    ("knn", KNeighborsRegressor(), kn_params),
    ("rf", RandomForestRegressor(), rf_params)
    ]

In [36]:
from sklearn.model_selection import RandomizedSearchCV
models = {}
for name,model,params in random_cv_model:
    rando = RandomizedSearchCV(estimator=model,
                               param_distributions=params,
                               n_iter=100,
                               cv=3,
                               n_jobs=-1)
    rando.fit(X_train,Y_train)
    models[name] = rando.best_estimator_, rando.best_score_

for name in models:
    print(f"---------------- Best Params for {name} -------------------")
    print(models[name])

/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_search.py:320: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

---------------- Best Params for knn -------------------
(KNeighborsRegressor(n_neighbors=10), 0.7770307943668874)
---------------- Best Params for rf -------------------
(RandomForestRegressor(max_features=5, n_estimators=200), 0.8613724189054427)

In [ ]:
for name in models:
    print(f"---------------- Best Params for {name} -------------------")
    print(models[name])