In [0]:
import seaborn as sns

In [0]:
df=sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [0]:
## now try to predict using naive byes by converting categorical into numerical

In [0]:
#independent and dependent feature
X=df[['sex']]
Y=df['time']
Y

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [0]:
#before moving on to perform one hot encoding for binary we first perform split of dataset

In [0]:
# Split the dataset into traintest split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)
# X_train.head()
Y_train.head()

171    Dinner
89      Lunch
157    Dinner
219    Dinner
234    Dinner
Name: time, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [0]:
# applying label encoding on traning data
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X_train['sex']=le1.fit_transform(X_train['sex'])
le2=LabelEncoder()
Y_train=le2.fit_transform(Y_train)
Y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0])

In [0]:
X_train

     sex
171    1
89     1
157    0
219    0
234    1
..   ...
67     0
192    1
117    0
47     1
172    1

[183 rows x 1 columns]

In [0]:
# applying same on testlabel encoding
X_test['sex']=le1.fit_transform(X_test['sex'])
Y_test=le2.fit_transform(Y_test)
Y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [0]:
from sklearn.naive_bayes import  GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,Y_train)

GaussianNB()

In [0]:
Y_Pred=gnb.predict(X_test)

In [0]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(Y_Pred,Y_test))
print("--------------")
print(confusion_matrix(Y_Pred,Y_test))
print("--------------")
print(classification_report(Y_Pred,Y_test))

0.7377049180327869
--------------
[[45 16]
 [ 0  0]]
--------------
              precision    recall  f1-score   support

           0       1.00      0.74      0.85        61
           1       0.00      0.00      0.00         0

    accuracy                           0.74        61
   macro avg       0.50      0.37      0.42        61
weighted avg       1.00      0.74      0.85        61

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [0]:
# completed successfully